// Generated by https://quicktype.io

export interface Hotels {
  id: string;
  name: string;
  country: string;
  city: string;
  price: number;
  images: string[];
  date_start: string;
  date_end: string;
  stars: number;
  rating: number;
  description: string;
}
